package love.nairain.huawei.config

/** 模块应用与目标进程共享的 schema v2 配置键。 */
object SettingsKeys {
    const val GROUP = "huawei_health_trim"
    const val SCHEMA_VERSION = "schema_version"
    const val CURRENT_SCHEMA_VERSION = 2

    // 仅这两个旧键继续沿用；旧版 row_* / tab_* 键有意不再读取。
    const val ENABLED = "enabled"
    const val HIDE_LAUNCHER_ICON = "hide_launcher_icon"

    const val HEALTH_SEARCH = "hide.health.search"
    const val HEALTH_MORE = "hide.health.more_menu"
    const val HEALTH_ACTIVITY_RINGS = "hide.health.activity_rings"
    const val HEALTH_QUICK_ENTRIES = "hide.health.quick_entries"
    const val HEALTH_EDIT_CARDS = "hide.health.edit_cards"
    const val HEALTH_TODAY = "hide.health.today_recommendation"
    const val HEALTH_INSIGHTS = "hide.health.insights"
    const val HEALTH_HEADLINES = "hide.health.headlines"
    const val HEALTH_TIPS = "hide.health.tips"

    const val SPORT_CATEGORY_BAR = "hide.sport.category_bar"
    const val SPORT_SEARCH = "hide.sport.search"
    const val SPORT_MORE = "hide.sport.more_menu"
    const val SPORT_BANNER = "hide.sport.banner"
    const val SPORT_STRETCH = "hide.sport.entry.stretch"
    const val SPORT_TRADITIONAL = "hide.sport.entry.traditional"
    const val SPORT_CYCLING = "hide.sport.entry.cycling"
    const val SPORT_GOLF = "hide.sport.entry.golf"
    const val SPORT_DANCE = "hide.sport.entry.dance"
    const val SPORT_PILATES = "hide.sport.entry.pilates"
    const val SPORT_ENJOY = "hide.sport.enjoy"
    const val SPORT_TODAY = "hide.sport.today"
    const val SPORT_MORE_COURSES = "hide.sport.more_courses"
    const val SPORT_COACHES = "hide.sport.coaches"

    const val DEVICE_SEARCH = "hide.device.search"
    const val DEVICE_MENU = "hide.device.menu"
    const val DEVICE_AUTO_UPGRADE = "hide.device.auto_upgrade_prompt"
    const val DEVICE_NEARBY_PERMISSION = "hide.device.nearby_permission_prompt"
    const val DEVICE_AUTO_SWITCH = "hide.device.auto_switch_prompt"
    const val DEVICE_SHARED = "hide.device.shared_prompt"
    const val DEVICE_ADD = "hide.device.add_device"
    const val DEVICE_LIST = "hide.device.device_list"
    const val DEVICE_FUNCTIONS = "hide.device.functions"
    const val DEVICE_WATCH_FACES = "hide.device.watch_faces"
    const val DEVICE_RECOMMENDED = "hide.device.recommended"
    const val DEVICE_MARKETING = "hide.device.marketing"
    const val DEVICE_STORE = "hide.device.store"

    const val MINE_MESSAGES = "hide.mine.messages"
    const val MINE_ACCOUNT = "hide.mine.account"
    const val MINE_VIP = "hide.mine.vip"
    const val MINE_MARKETING = "hide.mine.marketing"
    const val MINE_GROUP = "hide.mine.group"
    const val MINE_FAMILY = "hide.mine.family"
    const val MINE_ANNUAL_GOAL = "hide.mine.annual_goal"
    const val MINE_REPORTS = "hide.mine.reports"
    const val MINE_MEDALS = "hide.mine.medals"
    const val MINE_ACHIEVEMENTS = "hide.mine.achievements"
    const val MINE_DATA = "hide.mine.data"
    const val MINE_COURSES = "hide.mine.courses_plans"
    const val MINE_ACTIVITIES = "hide.mine.activities"
    const val MINE_ROUTES = "hide.mine.routes"
    const val MINE_PROFILE = "hide.mine.profile"
    const val MINE_ORDERS = "hide.mine.orders"
    const val MINE_ASSETS = "hide.mine.assets_rewards"
    const val MINE_IHEALTH = "hide.mine.ihealth_labs"
    const val MINE_SETTINGS = "hide.mine.settings"
    const val MINE_PRIVACY = "hide.mine.privacy"
    const val MINE_HELP = "hide.mine.help"
    const val MINE_FEEDBACK = "hide.mine.feedback"
    const val MINE_UPDATE = "hide.mine.update"
    const val MINE_ABOUT = "hide.mine.about"

    const val BOTTOM_HEALTH = "hide.bottom.health"
    const val BOTTOM_SPORT = "hide.bottom.sport"
    const val BOTTOM_MEMBER = "hide.bottom.member"
    const val BOTTOM_DEVICE = "hide.bottom.device"
    const val BOTTOM_MINE = "hide.bottom.mine"
}
